### ISSUE TITLE
按照文档 执行 goctl api new greet 并没有生成对应的文件

### ISSUE THREAD

**Issue by sunmouren** [tal-tech/zero-doc#51]
按照文档 执行 goctl api new greet ，实际生成的文件目录结构只有 etc目录、internal目录、和greet.api，并没有greet.go文件

**Comment by kevwan** [comment]
搞定了嘛？

**Comment by sunmouren** [comment]
搞定了，是一打开cmd就提示系统找不到指定路径的原因，修复这个就可以正常生成了。
