### ISSUE TITLE
goctl model mysql ddl -c -src shorturl.sql -dir . 生成文件有误

### ISSUE THREAD

**Issue by ymj4023** [tal-tech/zero-doc#53]
![1](https://user-images.githubusercontent.com/44188893/129328952-129d330c-599a-42d1-bbd1-07c1f2ae112e.png)
使用:goctl model mysql ddl -c -src shorturl.sql -dir . 命令生成的shorturl 少了一个t。文件内的short也是少了一个t
![3](https://user-images.githubusercontent.com/44188893/129328965-9432c10c-b52f-4143-81db-fc2a516878d1.png)

**Comment by fzf404** [comment]
看你的`shorturl.sql`文件，
应该是你写错了：create table `shorturl` 
写成了：create table `shorurl`

**Comment by ymj4023** [comment]
确实是里面写错了
