### ISSUE TITLE
无法将 'in.Shorten' (类型 string) 用作类型 sql.NullString

### ISSUE THREAD

**Issue by ymj4023** [tal-tech/zero-doc#55]
![企业微信截图_20210825173556](https://user-images.githubusercontent.com/44188893/130767079-8cabb0cb-0c22-4e11-a5c2-eac974d809d0.png)

**Comment by holdonbaby** [comment]
太巧了，我也报这个错了

**Comment by Ryanho84** [comment]
我也遇到这个问题，请问怎么解决呢？

**Comment by Ryanho84** [comment]
解决了。应该是生成代码的问题。把代码生成的变量类型sql.NullString全部手动改成string就可以了

**Comment by ymj4023** [comment]
我是把in转换成sql.NullString类型传进去
