### ISSUE TITLE
项目没人维护了吗？按照官方example根本行不通，服务跑不起来，报错

### ISSUE THREAD

**Issue by hs-llsong** [tal-tech/zero-doc#60]
按这个一步一步来 https://github.com/tal-tech/zero-doc/blob/main/docs/zero/bookstore.md 然后，根本行不通，项目没人维护了吗？

**Comment by kevwan** [comment]
积极维护呀，报什么错？

**Comment by anqiansong** [comment]
> 按这个一步一步来 https://github.com/tal-tech/zero-doc/blob/main/docs/zero/bookstore.md 然后，根本行不通，项目没人维护了吗？

我尽快看一下，感谢指出

**Comment by anqiansong** [comment]
> 按这个一步一步来 https://github.com/tal-tech/zero-doc/blob/main/docs/zero/bookstore.md 然后，根本行不通，项目没人维护了吗？

我重新走过一遍了，没有问题的，你是不是哪里搞错了，方便的话可以贴一下错误日志，我们针对性排查。

> TIPS
> 
> 示例不会把每一步都写详细的，比如import，go module依赖等

**Comment by kevwan** [comment]
> 按这个一步一步来 https://github.com/tal-tech/zero-doc/blob/main/docs/zero/bookstore.md 然后，根本行不通，项目没人维护了吗？

有错误你得说呀，就丢这么一句，我们得盲猜，你跑不对可能原因很多的，先关了，依然不对的话贴上错误打开我们马上看，谢谢！
