### ISSUE TITLE
doc/jwt.md  ，执行  goctl api go -api jwt.api -dir .   出现报错

### ISSUE THREAD

**Issue by KatePang13** [tal-tech/zero-doc#8]
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
github.com/tal-tech/go-zero/tools/goctl/api/parser.(*serviceEntityParser).parseLine(0xc000132100, 0xc0000a15c0, 0x1a, 0xc00012c000, 0xc000005ca0, 0x1, 0x1, 0x1, 0x20)
        C:/SDK/GoPath/pkg/mod/github.com/tal-tech/go-zero@v1.0.20/tools/goctl/api/parser/servicestate.go:108 +0x92e
github.com/tal-tech/go-zero/tools/goctl/api/parser.(*entity).process(0xc0000e6680, 0xc000132120, 0x20)
        C:/SDK/GoPath/pkg/mod/github.com/tal-tech/go-zero@v1.0.20/tools/goctl/api/parser/entity.go:123 +0x2dc
github.com/tal-tech/go-zero/tools/goctl/api/parser.(*serviceState).process(0xc000005c20, 0xc00012c000, 0xa98200, 0xc000005c20, 0x0, 0x0)
        C:/SDK/GoPath/pkg/mod/github.com/tal-tech/go-zero@v1.0.20/tools/goctl/api/parser/servicestate.go:38 +0x162
github.com/tal-tech/go-zero/tools/goctl/api/parser.(*Parser).Parse(0xc0000056a0, 0x7, 0xc0000056a0, 0x0)
        C:/SDK/GoPath/pkg/mod/github.com/tal-tech/go-zero@v1.0.20/tools/goctl/api/parser/parser.go:71 +0x136
github.com/tal-tech/go-zero/tools/goctl/api/gogen.DoGenProject(0xc000018110, 0x7, 0xdc8bae, 0x1, 0x0, 0x0, 0x0)
        C:/SDK/GoPath/pkg/mod/github.com/tal-tech/go-zero@v1.0.20/tools/goctl/api/gogen/gen.go:49 +0x67
github.com/tal-tech/go-zero/tools/goctl/api/gogen.GoCommand(0xc0000ca6e0, 0x0, 0xc000054630)
        C:/SDK/GoPath/pkg/mod/github.com/tal-tech/go-zero@v1.0.20/tools/goctl/api/gogen/gen.go:41 +0x155
github.com/urfave/cli.HandleAction(0x924c00, 0xa026d8, 0xc0000ca6e0, 0xc0000ca6e0, 0x0)
        C:/SDK/GoPath/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:526 +0xc5
github.com/urfave/cli.Command.Run(0x9d3af1, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x9ef67f, 0x2f, 0x0, ...)
        C:/SDK/GoPath/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:174 +0x52f
github.com/urfave/cli.(*App).RunAsSubcommand(0xc0000c2380, 0xc0000ca420, 0x0, 0x0)
        C:/SDK/GoPath/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:407 +0x889
github.com/urfave/cli.Command.startApp(0x9d3e6d, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x9e4f47, 0x1a, 0x0, ...)
        C:/SDK/GoPath/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:373 +0x84c
github.com/urfave/cli.Command.Run(0x9d3e6d, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x9e4f47, 0x1a, 0x0, ...)
        C:/SDK/GoPath/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:102 +0x9dd
github.com/urfave/cli.(*App).Run(0xc0000c21c0, 0xc000094000, 0x7, 0x8, 0x0, 0x0)
        C:/SDK/GoPath/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:279 +0x738
main.main()
        C:/SDK/GoPath/pkg/mod/github.com/tal-tech/go-zero@v1.0.20/tools/goctl/goctl.go:346 +0xd7

**Comment by kingxt** [comment]
麻烦贴一下你的api文件，我没有复现这个问题。

**Comment by KatePang13** [comment]
我直接copy文档里的api文件，报错了
```
type JwtTokenRequest struct {
}

type JwtTokenResponse struct {
  AccessToken  string `json:"access_token"`
  AccessExpire int64  `json:"access_expire"`
  RefreshAfter int64  `json:"refresh_after"` // 建议客户端刷新token的绝对时间
}

type GetUserRequest struct { 
  UserId string `json:"userId"`
}

type GetUserResponse struct {
  Name string `json:"name"`
}

service jwt-api {
  @handler JwtHandler
  post /user/token(JwtTokenRequest) returns (JwtTokenResponse)
}

@server(
  jwt: JwtAuth
)
service jwt-api {
  @handler GetUserHandler
  post /user/info(GetUserRequest) returns (GetUserResponse)
}
```

**Comment by kingxt** [comment]
我本地测试没问题，你更新下试试？

**Comment by kingxt** [comment]
> 我直接copy文档里的api文件，报错了
> 
> ```
> type JwtTokenRequest struct {
> }
> 
> type JwtTokenResponse struct {
>   AccessToken  string `json:"access_token"`
>   AccessExpire int64  `json:"access_expire"`
>   RefreshAfter int64  `json:"refresh_after"` // 建议客户端刷新token的绝对时间
> }
> 
> type GetUserRequest struct { 
>   UserId string `json:"userId"`
> }
> 
> type GetUserResponse struct {
>   Name string `json:"name"`
> }
> 
> service jwt-api {
>   @handler JwtHandler
>   post /user/token(JwtTokenRequest) returns (JwtTokenResponse)
> }
> 
> @server(
>   jwt: JwtAuth
> )
> service jwt-api {
>   @handler GetUserHandler
>   post /user/info(GetUserRequest) returns (GetUserResponse)
> }
> ```

我本地测试没问题，你更新下试试？

**Comment by kingxt** [comment]
> 我直接copy文档里的api文件，报错了
> 
> ```
> type JwtTokenRequest struct {
> }
> 
> type JwtTokenResponse struct {
>   AccessToken  string `json:"access_token"`
>   AccessExpire int64  `json:"access_expire"`
>   RefreshAfter int64  `json:"refresh_after"` // 建议客户端刷新token的绝对时间
> }
> 
> type GetUserRequest struct { 
>   UserId string `json:"userId"`
> }
> 
> type GetUserResponse struct {
>   Name string `json:"name"`
> }
> 
> service jwt-api {
>   @handler JwtHandler
>   post /user/token(JwtTokenRequest) returns (JwtTokenResponse)
> }
> 
> @server(
>   jwt: JwtAuth
> )
> service jwt-api {
>   @handler GetUserHandler
>   post /user/info(GetUserRequest) returns (GetUserResponse)
> }
> ```

你需要更新下goctl
